---
title: Ranvir's Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  thoughts:
    title: Archives
    output: true
name: Ranvir Singh
description: Open-source enthusiast.
avatar: https://singh1114.github.io/blog/images/project-management.svg
footer-links:
  dribbble:
  email: ranvir.singh1114@gmail.com
  facebook: "/profile.php?id=100006946710962"
  flickr:
  github: singh1114
  instagram:
  linkedin: ranvir-singh-153a21b0/
  pinterest:
  rss:
  twitter: ranvirsingh1114
  stackoverflow:
  youtube:
  googleplus:
disqus: ranvir-singh
google_analytics:
url: https://ranvir.xyz
baseurl: "/blog"
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: compressed
gems:
- jekyll-sitemap
- jekyll-redirect-from
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
theme: jekyll-theme-cayman
paginate: 10
paginate_path: "/posts/page:num/"
include:
- _categories
- _authors
- _thoughts
